export const ADD_BIG_PICTURE = "ADD_BIG_PICTURE"
export const DELETE_BIG_PICTURE = "DELETE_BIG_PICTURE"
export const ADD_ARGUMENT = "ADD_ARGUMENT"
export const DELETE_ARGUMENT = "DELETE_ARGUMENT"
export const ADD_RESOURCE = "ADD_RESOURCE"
export const PRO_ARGUMENT = 1
export const CON_ARGUMENT = 2