from back.models.basics.argument import Argument
from back.models.basics.argument import ArgumentSerializer
from back.models.basics.information import Information
from back.models.basics.information import InformationSerializer
from back.models.basics.problem import Problem
from back.models.basics.problem import ProblemSerializer
from back.models.basics.solution import Solution
from back.models.basics.solution import SolutionSerializer
from back.models.basics.bigpicture import BigPicture
from back.models.basics.bigpicture import BigPictureSerializer
