version: "3.7"

services:
  web:
    container_name: back
    build: ./back
    command: gunicorn api.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./back/:/opt/vuedensemble/back/
      - static_volume:/opt/vuedensemble/back/static
    expose:
      - 8000
    environment:
      - DEPLOYEMENT_MODE=local
      - SECRET_KEY=local
      - SQL_DATABASE=postgres
      - SQL_USER=postgres
      - SQL_PASSWORD=postgres
      - SQL_HOST=db
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:10.5-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  front:
    container_name: front
    build: ./front
    command: npm start 0.0.0.0:3000
    volumes:
      - ./front:/opt/vuedensemble/front/
    expose:
      - 3000

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/opt/vuedensemble/back/static
    ports:
      - 80:80
    depends_on:
      - web
      - front

volumes:
  static_volume:
