

// Authentication
export const LOGIN = "LOGIN"
export const LOGOUT = "LOGOUT"


// Notifications
export const ADD_NOTIFICATION = "ADD_NOTIFICATION"
export const POP_NOTIFICATION = "POP_NOTIFICATION"


// Ratings
export const ADD_RATING = "ADD_RATING"
export const CREATE_RATING = "CREATE_RATING"
export const DELETE_RATING = "DELETE_RATING"
export const ADD_RATING_RESULTS = "ADD_RATING_RESULTS"
export const ADD_GIVEN_REASON = "ADD_GIVEN_REASON"

export const ADD_REASON = "ADD_REASON"

// BigPictures
export const ADD_BIG_PICTURE = "ADD_BIG_PICTURE"
export const CREATE_BIG_PICTURE = "CREATE_BIG_PICTURE"
export const ADD_BIG_PICTURE_RESULTS = "ADD_BIG_PICTURE_RESULTS"
export const ADD_BIG_PICTURE_REFERENCE = "ADD_BIG_PICTURE_REFERENCE"
export const DELETE_BIG_PICTURE = "DELETE_BIG_PICTURE"


// Pagination
export const SET_GLOBAL_SUBJECT_COUNT = "SET_GLOBAL_SUBJECT_COUNT"
export const SET_GLOBAL_CATEGORY_COUNT = "SET_GLOBAL_CATEGORY_COUNT"
export const SET_CATEGORY_SUBJECT_COUNT = "SET_CATEGORY_SUBJECT_COUNT"
export const SET_BP_REASON_COUNT = "SET_BP_REASON_COUNT"
export const SET_OWN_SUBJECT_COUNT = "SET_OWN_SUBJECT_COUNT"
export const SET_BP_REFERENCE_COUNT = "SET_BP_REFERENCE_COUNT"
export const SET_OWN_RATING_COUNT = "SET_OWN_RATING_COUNT"
export const SET_RATING_RATING_COUNT = "SET_RATING_RATING_COUNT"
export const SET_BP_RATING_COUNT = "SET_BP_RATING_COUNT"
export const SET_USER_RATING_COUNT = "SET_USER_RATING_COUNT"
export const SET_OWN_SUBSCRIPTION_COUNT = "SET_OWN_SUBSCRIPTION_COUNT"
export const SET_ENDORSMENT_COUNT = "SET_ENDORSMENT_COUNT"
export const SET_BP_ENDORSMENT_COUNT = "SET_BP_ENDORSMENT_COUNT"
export const SET_USER_ENDORSMENT_COUNT = "SET_USER_ENDORSMENT_COUNT"
export const SET_SUBJECT_RATING_COUNT = "SET_SUBJECT_RATING_COUNT"

// Users
export const ADD_USER = "ADD_USER"
export const ADD_SUBSCRIPTION = "ADD_SUBSCRIPTION"
export const CREATE_SUBSCRIPTION = "CREATE_SUBSCRIPTION"
export const DELETE_SUBSCRIPTION = "DELETE_SUBSCRIPTION"
export const ADD_ENDORSMENT = "ADD_ENDORSMENT"
export const DELETE_ENDORSMENT = "DELETE_ENDORSMENT"

// Categories
export const ADD_CATEGORY = "ADD_CATEGORY"

// Requests
export const ADD_REQUEST = "ADD_REQUEST"
export const REQUEST_CREATED = "REQUEST_CREATED"
export const REQUEST_ONGOING = "REQUEST_ONGOING"
export const REQUEST_DONE = "REQUEST_DONE"
export const REQUEST_PROCESSED = "REQUEST_PROCESSED"

