

export const SOCIALS = "Réseaux sociaux"
export const USER = "Utilisateur"
export const CONTENT = "Mes contenus"
export const DISCONNECT = "Déconnexion"
export const CREATE = "Créer"
export const DESCRIPTION = "Description"
export const CHILDREN = "Descendance"
export const REASONS_MENU = "Menu des Raisons"
export const SHOW_REASONS = "Afficher les raisons"
export const CREATE_REASON = "Créer une raison"
export const ADD_CHILD = "Créer une vue enfant"
export const SHOW_RESULTS = "Afficher les résultats"
export const SHOW_ENDORSMENTS = "Afficher les évaluations"
export const EDIT_BP = "Modifier cette vue"
export const LOOK = "Aller sur la page dédiée"
