


export const MSG_NO_SUBJECT = "Aucun sujet n'a encore été créé."
export const MSG_NO_REFERENCE = "Cette vue d'ensemble n'a encore été référencée nulle part sur VDE."
export const MSG_NO_REASON = "Cette vue d'ensemble n'a pas encore été raisonnée."
export const REFERENCE_LIST_TITLE = "Références"
export const REASON_LIST_TITLE = "Commentaires"
export const USER_EMPTY_BIO = (username) => `${username} n'a pas renseigné sa bio.`
export const USER_HAS_NO_SUBJECT = (username) => `Aucun sujet n'a encore été créé publiquement par ${username}`
export const USER_HAS_NO_REASON = (username) => `Aucune raison n'a encore été donnée publiquement par ${username}`
export const USER_BIO_PLACEHOLDER = "Présentez-vous en quelques mots !"
export const CREATED_SUBJECT_LIST_TITLE = "Sujets créés"
export const CREATED_REASON_LIST_TITLE = "Raisons données"
export const SUBSCRIPTION_LIST_TITLE = "Abonnements"
export const USER_HAS_NO_SUBSCRIPTION = "Vous ne vous êtes encore abonné à personne."
export const RATING_HAS_NO_RATING = "Cette raison n'a pas encore été raisonnée..."
export const RATING_HAS_NO_ENDORSMENT = "Cette raison n'a encore été évaluée par personne..."
export const BP_HAS_NO_ENDORSMENT = "Cette vue d'ensemble n'a encore été évaluée par personne..."
export const BP_EMPTY_BODY = "Aucun élément n'a encore été apporté pour préciser cette vue d'ensemble."
export const CONTEXT_TITLE = "Contexte"
export const RESULTS_TITLE = "Résultats"
export const GUEST_NAME = "Invité"
export const ENDORSMENT_LIST_TITLE = "Évaluations"
export const CHILD_LIST_TITLE = "Analyse"
export const CREATE_BP_MODAL_TITLE = "Création d'une nouvelle vue d'ensemble"
export const CREATE_RATING_MODAL_TITLE = "Création d'une nouvelle raison"
export const CREATE_ENDORSMENT_MODAL_TITLE = "Création d'une nouvelle évaluation"
export const EDIT_RATING_MODAL_TITLE = "Modification d'une raison"
export const EDIT_BP_MODAL_TITLE = "Modification d'une vue d'ensemble"
export const DISCONNECT = "Déconnexion"
export const PROFILE = "Profil"
export const USERNAME = "Nom d'utilisateur"
export const PASSWORD = "Mot de passe"
export const INSCRIPTION_LINK = "Ou inscrivez-vous ici."
export const CAN_NOT_ADD_BP_CHILDREN_AT_CREATION = "Vous pourrez ajouter des éléments à hiérarchiser une fois que votre vue d'ensemble sera créée."
export const SHOW_CONTENT = "Afficher le contenu"
export const HIDE_CONTENT = "Masquer le contenu"
export const SHOW_CHILDREN = "Afficher l'analyse"
export const HIDE_CHILDREN = "Masquer l'analyse"
export const SHOW_REASONS = "Afficher les raisons"
export const HIDE_REASONS = "Masquer les raisons"
export const SHOW_RESULTS = "Afficher les résultats"
export const HIDE_RESULTS = "Masquer les résultats"
export const SHOW_ENDORSMENTS = "Afficher les évaluations"
export const HIDE_ENDORSMENTS = "Masquer les évaluations"
export const SHOW_REFERENCES = "Afficher les références"
export const HIDE_REFERENCES = "Masquer les références"
export const CREATE_REASON = "Créer une raison"
export const CREATE_ENDORSMENT = "Évaluer sur la base de cette raison"

export const CREATE_BP_ENDORSMENT_BY_KIND = {
  1: "Évaluer ce sujet.",
  2: "Évaluer ce problème.",
  3: "Évaluer cette solution.",
  4: "Évaluer cette ressource."
}
export const ADD_CHILD = "Créer une vue enfant"
export const EDIT_BP = "Modifier cette vue"
export const EDIT_RATING = "Modifier cette raison"
export const LAST_ACTIVITY_BP = "Activité (vues)"
export const NO_ACTIVITY_BP = "Aucune vue n'a encore été ajoutée à ce sujet."
export const LAST_ACTIVITY_RATING = "Activité (raisons)"
export const NO_ACTIVITY_RATING = "Aucune raison n'a encore été apportée à ce sujet."
export const SEE_MORE = "Voir plus"
export const SEE_LESS = "Voir moins"
export const REASON_FIELD_MODAL_TITLE = "Écrivez votre propre commentaire"
export const NEW_REASON_PLACEHOLDER = "Écrivez votre propre commentaire !"
