# Generated by Django 2.2.9 on 2020-02-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigpicture',
            name='title',
            field=models.CharField(max_length=380),
        ),
    ]
