# Generated by Django 2.2.10 on 2020-02-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200214_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigpicture',
            name='kind',
            field=models.IntegerField(choices=[('subject', 1), ('problem', 2), ('solution', 3), ('resource', 4)]),
        ),
    ]
