# Generated by Django 2.2.10 on 2020-04-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200228_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='bio',
            field=models.TextField(default=''),
        ),
    ]
