# Generated by Django 2.2.10 on 2020-05-19 21:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_baseuser_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endorsment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0.0)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='rating',
            name='unique_rating_on_rating',
        ),
        migrations.RemoveConstraint(
            model_name='rating',
            name='unique_rating_on_bp',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='reason',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='endorsment',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='value',
        ),
        migrations.AlterField(
            model_name='rating',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='endorsment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='endorsment',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsments', to='api.Rating'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', through='api.Subscription', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('target', 'author'), name='unique_subscriptions'),
        ),
        migrations.AddConstraint(
            model_name='endorsment',
            constraint=models.UniqueConstraint(fields=('target', 'author'), name='unique_endorsment'),
        ),
    ]
