# Generated by Django 2.2.13 on 2020-06-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200519_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigpicture',
            name='pin',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
