# Generated by Django 2.2.13 on 2020-08-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200812_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='modification_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
