# Generated by Django 2.2.13 on 2020-08-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200817_1028'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='endorsment',
            constraint=models.UniqueConstraint(fields=('author', 'bigpicture'), name='unique_endorsment_bp'),
        ),
        migrations.AddConstraint(
            model_name='endorsment',
            constraint=models.UniqueConstraint(fields=('author', 'rating'), name='unique_endorsment_rtg'),
        ),
    ]
