# Generated by Django 2.2.13 on 2020-08-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_bigpicture_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.AlterField(
            model_name='category',
            name='label',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
