# Generated by Django 2.2.13 on 2020-09-01 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200827_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bigpicture',
            name='kind',
        ),
    ]
