# Generated by Django 2.1.7 on 2019-03-02 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BigPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('hashtags', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('bigpicture_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='back.BigPicture')),
                ('nature', models.IntegerField(choices=[(1, 'pro'), (2, 'con')])),
            ],
            bases=('back.bigpicture',),
        ),
        migrations.AddField(
            model_name='bigpicture',
            name='resourceFor',
            field=models.ForeignKey(blank=True, null=True, on_delete=False, related_name='resources', to='back.BigPicture'),
        ),
        migrations.AddField(
            model_name='argument',
            name='bigPicture',
            field=models.ForeignKey(on_delete=True, related_name='arguments', to='back.BigPicture'),
        ),
    ]
