name: Django CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: dschep/install-pipenv-action@v1
  
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies with pipenv
      run: |
        pip install pipenv
        cd back
        pipenv install --deploy --dev
        
    - name: Run tests
      run: |
        pipenv shell
        cd back
        python manage.py test

